;;;Yatex auto fill
(setq YaTeX-greek-key-alist-private
       '(("v" "varphi" "φ-")
	 ("f" "phi" "φ")
	 ("F" "Phi" "Φ")
	 ("h" "eta" "η")
	 ("vb" "vb*" "vector greek")
	 ("vth" "vb*{\\theta}" "vector θ")
	 ("OO" "mho" "~|_|~")
	 ;("<" "bra{" "<~|")
	 ;(">" "ket{" "|~>")
	 ))
;;;;
;;数式モードの";"補間の強化
(setq YaTeX-math-sign-alist-private
      '(("q"         "quad"          "__")
	("qq"        "qquad"         "____")
	("l-"        "varlimsup"     "___\nlim")
	("l_"        "varliminf"     "lim\n---")
	("il"        "varinjlim"     "lim\n-->")
       ;("st"        "text{ s.~t. }" "s.t.")
	("pl"        "varprojlim"    "lim\n<--")
	("|V"        "downarrow"    " |\n V")
	("H" "mathcal{H}" "Hilbert sp")
	("Q" "mathbb{Q}" "ℚ")
	("Z" "mathbb{Z}" "ℤ")
	("R" "mathbb{R}" "ℝ")
	("C" "mathbb{C}" "ℂ")
	("N" "mathbb{N}" "ℕ")
	(">->" "rightarrowtail" "↣")
	("->>" "twoheadrightarrow" "↠")
	("'" "dot" "・\n~")
	("''" "ddot" "・・\n~")
	("n" "nonumber\\\\" "*\\")
	;with physics package
	("b" "bra" "<~|")
	("k" "ket" "|~>")
	;("<>" "braket" "<~|~>")
	("bk" "braket" "<~|*>")
	("p" "dyad" "|~><~|")
	("kb" "ketbra" "|~><*|")
	("e" "ev" "<~|O|~> (O of ~)")
	("m" "mel" "<~|O|*>")
	("tr" "tr" "tr")
	("Tr" "Tr" "Tr")
	("||" "norm" "||~||")
	("/6" "pdv" "∂\n---\n ∂~")
	("/d" "dv" "d\n---\n d~")
	("d" "dd" "d")
	("fd" "fdv" "func der")
	("cc" "qcc" "_c.c._")
	("if" "qif" "_if_")
	("O" "order" "O()")
	("[]" "comm" "[,]")
	("{}" "acomm" "{,}")
	("v" "vb" "vector bold")
	("v*" "vb*" "vector greek(italic)")
	))
;;数式モードの","補間
(setq YaTeX-math-funcs-list
      '(("s"	"sin"           "sin")
	("c"    "cos"           "cos") 
	("t"    "tan"           "tan")
	("hs"	"sinh"          "sinh")
	("hc"   "cosh"          "cosh")
	("ht"   "tanh"          "tanh")
	("S"	"arcsin"        "arcsin")
	("C"    "arccos"        "arccos")
	("T"    "arctan"        "arctan")
	("se"   "sec"           "sec")
	("cs"   "csc"           "csc")
	("cot"  "cot"           "cot")
	("l"    "log"            "log")
	("L"    "ln"           "ln")
	("e"    "exp"           "exp")
	("M"    "max"           "max")
	("m"    "min"           "min")
	("su"   "sup"           "sup")
	("in"   "inf"           "inf")
	("di"   "dim"           "dim")
	("de"   "det"           "det")
	("i"    "Im"       "Im")
	("r"    "Re"       "Re")
	("BB"   "vb{B}"    "vector B")
	("<"    "langle"  "<")
	(">"    "rangle"  ">")
	("[c"    "left\lceil"  " _\n|")
	("]c"    "right\\rceil"  "_\n |")
	("["    "left\lfloor"  "|\n--")
	("]"    "right\\rfloor"  " |\n--")
	;("i" "imath"             "i")
	;("j"   "jmath"           "j")
	;("I"    "Im"            "Im")
	;("R"    "Re"            "Re")
	))

(setq YaTeX-math-key-list-private
      '(("'" . YaTeX-math-funcs-list)))

 (setq yatex-mode-load-hook
       '(lambda()
	  (YaTeX-define-begend-key "ba" "align")
	  (YaTeX-define-begend-key "bA" "align*")
	  ;theorems
	  (YaTeX-define-begend-key "bp" "proof")
	  (YaTeX-define-begend-key "bt" "theorem")
	  (YaTeX-define-begend-key "bl" "lemma")
	  (YaTeX-define-begend-key "bd" "definition")
	  (YaTeX-define-begend-key "bP" "proposition")
	  (YaTeX-define-begend-key "bD" "document")
	  (YaTeX-define-begend-key "bC" "corollary")
	  ))
