name: "CI"
on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - '**.org'
    - '.dir-locals.el'
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version: [27.1, 27.2, snapshot]
        exclude:
          - os: macos-latest
            emacs_version: 23.4
          - os: macos-latest
            emacs_version: 24.2

    steps:
    - uses: actions/checkout@v2


    - name: Check emacs version
      run: emacs --version
    - name: Check nix tools visible
      run: "nix-shell -p cowsay --run 'cowsay hello'"
